version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "5173:5173"
